# -*- mode: python ; coding: utf-8 -*-
# LifeOS PyInstaller Spec

import os
import sys

block_cipher = None

a = Analysis(
    ['app/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app/prompts', 'app/prompts'),
        ('.env.example', '.'),
    ],
    hiddenimports=[
        'app',
        'app.main',
        'app.config',
        'app.config.settings',
        'app.database',
        'app.database.sqlite',
        'app.database.migrations',
        'app.database.repositories',
        'app.ingestion',
        'app.ingestion.scanner',
        'app.ingestion.processor',
        'app.extraction',
        'app.extraction.metadata',
        'app.extraction.text_extractor',
        'app.chunking',
        'app.chunking.chunker',
        'app.embeddings',
        'app.embeddings.local',
        'app.search',
        'app.search.hybrid',
        'app.search.semantic',
        'app.search.keyword',
        'app.search.ranking',
        'app.search.graph_search',
        'app.search.global_search',
        'app.ai',
        'app.ai.gemini_provider',
        'app.ai.openai_provider',
        'app.ai.factory',
        'app.ai.prompts',
        'app.ai.context_builder',
        'app.ai.smart_context',
        'app.ai.smart_systems',
        'app.memory',
        'app.memory.store',
        'app.memory.searcher',
        'app.projects',
        'app.projects.manager',
        'app.git',
        'app.git.tracker',
        'app.git.memory_linker',
        'app.ocr',
        'app.ocr.engine',
        'app.code_intelligence',
        'app.code_intelligence.analyzer',
        'app.code_intelligence.context_provider',
        'app.code_intelligence.dependencies',
        'app.graph',
        'app.graph.graph_builder',
        'app.graph.graph_widget',
        'app.models',
        'app.models.document',
        'app.models.chunk',
        'app.models.project',
        'app.models.search',
        'app.gui',
        'app.gui.main_window',
        'app.gui.search_widget',
        'app.gui.ask_widget',
        'app.gui.projects_widget',
        'app.gui.memory_widget',
        'app.gui.timeline_widget',
        'app.gui.graph_page',
        'app.gui.bulk_widget',
        'app.gui.settings_widget',
        'app.gui.auto_complete',
        'app.gui.notifications',
        'app.gui.theme',
        'app.gui.styles',
        'app.gui.dashboard',
        'app.gui.dashboard_widget',
        'app.cli',
        'app.cli.commands',
        'PySide6',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'sentence_transformers',
        'faiss',
        'numpy',
        'fitz',
        'requests',
        'bs4',
        'tiktoken',
        'networkx',
        'pytesseract',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='lifeos',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='lifeos',
)
